# Site settings
title: oxnan
email: contact@oxnan.com
description: Official site for the oxnan company
baseurl: "./" # the subpath of your site, e.g. /blog
url: "oxnan.com" # the base hostname & protocol for your site

# Identity
your-name: oxnan
your-title: For all your general IT needs

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
