# Site settings
title: Elaine Wong
email: lainermeister@gmail.com
description: FinTech software engineer with background in consulting, startups, & engineering
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Identity
your-name: Elaine Wong
your-title: Software Engineer

# Social settings
500px_url:
github_url: https://github.com/lainermeister
instagram_url: https://instagram.com/lainermeister
linkedin_url: https://www.linkedin.com/in/elaineywong/

# Build settings
markdown: kramdown
